account/urls.py
from django.urls import path, re_path
import account.views as views

urlpatterns = [
    path('index/', views.index, name='index'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('email_active/', views.email_active, name='email_active'),
    path('send_change_password_mail/', views.send_change_password_mail, name='send_change_password_mail'),
    path('change_password/', views.change_password, name='change_password'),
    path('forget/', views.forget, name='forget'),
    path('hello/', views.hello, name='hello'),
    re_path(r'image/code/$', views.image_code, name='image_code'),
]

examOnline/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('account/', include(('account.urls', 'account'), namespace='account')),
                  path('question_bank/', include(('question_bank.urls', 'question_bank'), namespace='question_bank')),
                  re_path(r'^ckeditor/', include('ckeditor_uploader.ckeditor_urls')),
                  # 此处修改ckeditor源码取消验证url.py改成ckeditor_urls，将staff_member_required去掉
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 没有这一句无法显示上传的图片

question_bank/urls.py
from django.urls import path, re_path
from question_bank.views import bank
from question_bank.views import question

urlpatterns = [
    # 题库
    path('bank_list/', bank.bank_list, name='bank_list'),
    path('bank_add/', bank.bank_add, name='bank_add'),
    re_path(r'bank_edit/(?P<pk>\d+)/$', bank.edit, name='bank_edit'),
    re_path(r'bank_delete/(?P<pk>\d+)/$', bank.delete, name='bank_delete'),
    # 题
    path('question_list/', question.question_list, name='question_list'),
    re_path(r'question_add/', question.question_add, name='question_add'),
    re_path(r'question_edit/(?P<pk>\d+)/$', question.question_change, name='question_edit'),
    path(r'get_question_options/', question.get_question_options, name='get_question_options'),
    re_path(r'question_delete/(?P<pk>\d+)/$', question.question_delete, name='question_delete'),
    path('import_question/', bank.import_question, name='import_question'),
]

utils/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from django.urls import reverse
from django.http import QueryDict


def memory_url(request, name, *args, **kwargs):
    """
    生成带有原搜索条件的URL（替代了模板中的url）
    :param request:
    :param name:
    :return:
    """
    basic_url = reverse(name, args=args, kwargs=kwargs)

    # 当前URL中无参数
    if not request.GET:
        return basic_url

    query_dict = QueryDict(mutable=True)
    query_dict['_filter'] = request.GET.urlencode()  # mid=2&age=99

    return "%s?%s" % (basic_url, query_dict.urlencode())


def memory_reverse(request, name, *args, **kwargs):
    """
    反向生成URL
        http://127.0.0.1:8001/rbac/menu/add/?_filter=mid%3D2
        1. 在url中讲原来搜索条件，如filter后的值
        2. reverse生成原来的URL，如：/menu/list/
        3. /menu/list/?mid%3D2

    示例：
    :param request:
    :param name:
    :param args:
    :param kwargs:
    :return:
    """
    url = reverse(name, args=args, kwargs=kwargs)
    origin_params = request.GET.get('_filter')

    if origin_params:
        url = "%s?%s" % (url, origin_params,)

    return url

account/forms/file.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from django import forms
from django.core.exceptions import ValidationError
from web.forms.bootstrap import BootStrapForm
from web import models


class FolderModelForm(BootStrapForm, forms.ModelForm):
    class Meta:
        model = models.FileRepository
        fields = ['name']

    def __init__(self, request, parent_object, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request
        self.parent_object = parent_object

    def clean_name(self):
        name = self.cleaned_data['name']

        # 数据库判断 当前目录 下此 文件夹是否已存在
        queryset = models.FileRepository.objects.filter(file_type=2, name=name, project=self.request.tracer.project)
        if self.parent_object:
            exists = queryset.filter(parent=self.parent_object).exists()
        else:
            exists = queryset.filter(parent__isnull=True).exists()
        if exists:
            raise ValidationError('文件夹已存在')
        return name


class FileModelForm(forms.ModelForm):
    etag = forms.CharField(label='ETag')

    class Meta:
        model = models.FileRepository
        exclude = ['project', 'file_type', 'update_user', 'update_datetime']

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.request = request

    def clean_file_path(self):
        return "https://{}".format(self.cleaned_data['file_path'])

    """
    def clean(self):
        key = self.cleaned_data['key']
        etag = self.cleaned_data['etag']
        size = self.cleaned_data['size']

        if not key or not etag:
            return self.cleaned_data

        # 向COS校验文件是否合法
        # SDK的功能
        from qcloud_cos.cos_exception import CosServiceError
        try:
            result = check_file(self.request.tracer.project.bucket, self.request.tracer.project.region, key)
        except CosServiceError as e:
            self.add_error("key", '文件不存在')
            return self.cleaned_data

        cos_etag = result.get('ETag')
        if etag != cos_etag:
            self.add_error('etag', 'ETag错误')

        cos_length = result.get('Content-Length')
        if int(cos_length) != size:
            self.add_error('size', '文件大小错误')

        return self.cleaned_data
    """

account/forms/issues.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from django import forms
from web.forms.bootstrap import BootStrapForm
from web import models


class IssuesModelForm(BootStrapForm, forms.ModelForm):
    class Meta:
        model = models.Issues
        exclude = ['project', 'creator', 'create_datetime', 'latest_update_datetime']
        widgets = {
            "assign": forms.Select(attrs={'class': "selectpicker", "data-live-search": "true"}),
            "attention": forms.SelectMultiple(
                attrs={'class': "selectpicker", "data-live-search": "true", "data-actions-box": "true"}),
            "parent": forms.Select(attrs={'class': "selectpicker", "data-live-search": "true"}),
            "start_date": forms.DateTimeInput(attrs={'autocomplete': "off"}),
            "end_date": forms.DateTimeInput(attrs={'autocomplete': "off"})
        }

    def __init__(self, request, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # 处理数据初始化

        # 1.获取当前项目的所有问题类型 [(1,'xx'),(2,"xx")]
        self.fields['issues_type'].choices = models.IssuesType.objects.filter(
            project=request.tracer.project).values_list('id', 'title')

        # 2.获取当前项目的所有模块
        module_list = [("", "没有选中任何项"), ]
        module_object_list = models.Module.objects.filter(project=request.tracer.project).values_list('id', 'title')
        module_list.extend(module_object_list)
        self.fields['module'].choices = module_list

        # 3.指派和关注者
        # 数据库找到当前项目的参与者 和 创建者
        total_user_list = [(request.tracer.project.creator_id, request.tracer.project.creator.username), ]
        project_user_list = models.ProjectUser.objects.filter(project=request.tracer.project).values_list('user_id',
                                                                                                          'user__username')
        total_user_list.extend(project_user_list)

        self.fields['assign'].choices = [("", "没有选中任何项")] + total_user_list
        self.fields['attention'].choices = total_user_list

        # 4. 当前项目已创建的问题
        parent_list = [("", "没有选中任何项")]
        parent_object_list = models.Issues.objects.filter(project=request.tracer.project).values_list('id', 'subject')
        parent_list.extend(parent_object_list)
        self.fields['parent'].choices = parent_list


class IssuesReplyModelForm(forms.ModelForm):
    class Meta:
        model = models.IssuesReply
        fields = ['content', 'reply']


class InviteModelForm(BootStrapForm, forms.ModelForm):
    class Meta:
        model = models.ProjectInvite
        fields = ['period', 'count']

account/views.py
import time
from io import BytesIO
from django.shortcuts import render, HttpResponse, redirect
from django.conf import settings
from django.db.models import Q
from account.forms.account import RegisterModelForm, LoginForm, ChangePasswordForm, ForgetPasswordForm
from account import models
from account.utils.image_code import check_code
from django.core.mail import send_mail
from django.utils.safestring import mark_safe
from django.urls import reverse
import jwt


class UserInfo(object):

    def __init__(self, user=None):
        self.user = user


def get_base_url(request):
    """
    Get base URL from the request
    """
    host = request.get_host()
    if ":" not in host:
        # tricky here: when used with nginx+uwsgi, port is not included
        host += ":" + request.get_port()
    return request.scheme + "://" + host


def make_token(data):
    d = {
        'exp': time.time() + settings.TOKEN_EXPIRE,
        'iat': time.time(),
        'iss': 'mling17',
        'data': data
    }
    return jwt.encode(d, settings.SECRET_KEY, algorithm='HS256')


def send_email(request, subject, to_email, token, type):
    """
    发送邮件
    :param request:
    :param subject:
    :param to_email:
    :param token:
    :param type: 0.注册（register）；1.修改密码（change）；2.找回密码（forget）
    :return:
    """
    from_email = settings.EMAIL_FROM  # 发件人，在settings.py中已经配置
    # 发送的消息
    message = ''  # 发送普通的消息使用的时候message
    base_url = get_base_url(request)
    if type == 'register':
        meg_html = f'<p>请点击下面的链接激活你的账号(有效时间{settings.TOKEN_EXPIRE // 3600}小时):</p><a href="{base_url}{reverse("account:email_active")}?token={token}">{base_url}{reverse("account:email_active")}?token={token}</a>'  # 发送的是一个html消息 需要指定
    elif type == 'change':
        meg_html = f'<p>请点击下面的链接修改密码(有效时间{settings.TOKEN_EXPIRE // 3600}小时):</p><a href="{base_url}{reverse("account:change_password")}?token={token}">{base_url}{reverse("account:change_password")}?token={token}</a>'  # 发送的是一个html消息 需要指定
    elif type == 'forget':
        meg_html = f'<p>请点击下面的链接重置密码(有效时间{settings.TOKEN_EXPIRE // 3600}小时):</p><a href="{base_url}{reverse("account:forget")}?token={token}">{base_url}{reverse("account:forget")}?token={token}</a>'  # 发送的是一个html消息 需要指定
    else:
        raise ValueError('type param want (register,change,forget),get %s' % type)
    send_mail(subject, message, from_email, [to_email], html_message=meg_html)
    return True


def index(request):
    return render(request, 'index.html')


def register(request):
    """注册视图"""
    if request.method == 'GET':
        form = RegisterModelForm(request)
        return render(request, 'register.html', {'form': form})
    form = RegisterModelForm(request, request.POST)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        email = form.cleaned_data.get('email')
        mobile_phone = form.cleaned_data.get('mobile_phone')
        nickname = password[:8]
        data = {'email': email, }
        token = make_token(data)
        send_email(request, subject='账号激活', to_email=email, token=token, type='register')
        email_obj = models.EmailVerifyRecord()
        email_obj.email = email
        email_obj.token = token
        email_obj.m_type = 0
        email_obj.save()
        user = models.User()
        user.username = username
        user.password = password
        user.email = email
        user.mobile_phone = mobile_phone
        user.nickname = nickname
        user.save()
        context = {'msg': '注册成功，请登录邮箱激活账号。', 'next_pg': None}
        return render(request, 'common_msg.html', context=context)
    return render(request, 'register.html', {'form': form})


def email_active(request):
    token = request.GET.get('token')
    try:
        record = models.EmailVerifyRecord.objects.filter(token=token, is_valid=True).first()
        if record:
            models.EmailVerifyRecord.objects.filter(token=token).update(is_valid=False)
            user = models.User.objects.filter(email=record.email).first()
            user.mail_valid = True
            user.save()
            request.session['user_id'] = user.id
            request.user_info = UserInfo(user)
            context = {'msg': '邮箱激活成功,3秒后自动跳转', 'next_pg': reverse('account:index')}
            return render(request, 'common_msg.html', context=context)
        else:
            return HttpResponse('邮箱验证错误或链接已失效')
    except jwt.exceptions.ExpiredSignatureError:
        models.EmailVerifyRecord.objects.filter(token=token).update(is_valid=False)
        return HttpResponse(mark_safe('<input type="text" name="email" placeholder="邮箱">'))  # todo token过期的情况处理


def login(request):
    """ 用户名和密码登录 """
    if request.method == 'GET':
        if request.session.get('user_id'):
            return redirect('account:index')
        form = LoginForm(request)
        return render(request, 'login.html', {'form': form})
    form = LoginForm(request, data=request.POST)
    if form.is_valid():
        username = form.cleaned_data['username']
        password = form.cleaned_data['password']
        user_object = models.User.objects.filter(Q(username=username) | Q(mobile_phone=username) | Q(email=username)) \
            .filter(password=password).first()
        if user_object:
            request.session['user_id'] = user_object.id
            request.session.set_expiry(settings.SESSION_EXPIRE)
            return redirect(settings.SIGNED_DIRECT)
        form.add_error('username', '用户名或密码错误')

    return render(request, 'login.html', {'form': form})


def image_code(request):
    """ 生成图片验证码 """
    image_object, code = check_code()
    request.session['image_code'] = code
    request.session.set_expiry(60)  # 主动修改session的过期时间为60s
    stream = BytesIO()
    image_object.save(stream, 'png')
    return HttpResponse(stream.getvalue())


def logout(request):
    request.session.flush()
    return redirect(settings.SIGNED_DIRECT)


def send_change_password_mail(request):
    email = request.user_info.user.email
    data = {'email': email, }
    token = make_token(data)
    send_email(request, '修改密码', email, token=token, type='change')
    email_user, domain = email.split('@')
    email_str = email_user[:2] + '***' + email[-1] + '@' + domain
    record_obj = models.EmailVerifyRecord(email=email, token=token, m_type=1)
    record_obj.save()
    return HttpResponse(f'修改密码链接已发送到您的邮箱：{email_str}，请点击邮箱链接进行修改。')


def change_password(request):
    if request.method == 'GET':
        form = ChangePasswordForm(request)
        token = request.GET.get('token')
        try:
            if models.EmailVerifyRecord.objects.filter(token=token, is_valid=True).exists():
                return render(request, 'change_password.html', {'form': form, 'token': token})
            raise jwt.exceptions.ExpiredSignatureError
        except jwt.exceptions.ExpiredSignatureError:
            return HttpResponse('链接已失效')
    form = ChangePasswordForm(request, request.POST)
    if form.is_valid():
        token = request.POST.get('token')
        new_pwd = form.cleaned_data.get('password')
        record_obj = models.EmailVerifyRecord.objects.filter(token=token).first()
        record_obj.is_valid = False
        record_obj.save()
        models.User.objects.filter(email=record_obj.email).update(password=new_pwd)
        context = {'next_pg': reverse('account:login'), 'msg': '密码修改成功,请重新登录'}
        request.session.flush()
        return render(request, 'common_msg.html', context=context)
    return render(request, 'change_password.html', {'form': form})


def forget(reqeust):
    if reqeust.method == 'GET':
        token = reqeust.GET.get('token')
        if token:
            record = models.EmailVerifyRecord.objects.filter(token=token, m_type=2, is_valid=True).first()
            try:
                data = jwt.decode(token, settings.SECRET_KEY, issuer='mling17', algorithms='HS256')['data']
                email = data.get('email')
                password = data.get('password')
                record.is_valid = False
                record.save()
                models.User.objects.filter(email=email).update(password=password)
                context = {'msg': '密码重置成功，请重新登录。', 'next_pg': reverse('account:login')}
                return render(reqeust, 'common_msg.html', context=context)
            except (jwt.exceptions.ExpiredSignatureError, jwt.exceptions.DecodeError, AttributeError):
                return HttpResponse('链接失效')
        form = ForgetPasswordForm(reqeust)
        return render(reqeust, 'change_password.html', {'form': form})
    form = ForgetPasswordForm(reqeust, reqeust.POST)
    if form.is_valid():
        email = form.cleaned_data.get('email')
        password = form.cleaned_data.get('password')
        data = {'email': email, 'password': password}
        token = make_token(data)
        models.EmailVerifyRecord.objects.create(email=email, token=token, m_type=2)
        send_email(reqeust, '重置密码', email, token, 'forget')
        context = {'msg': '重置密码邮件已发送，请前往邮箱点击重置链接。'}
        return render(reqeust, 'common_msg.html', context=context)
    return render(reqeust, 'change_password.html', {'form': form})


def hello(request):
    return HttpResponse('hello')

account/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>{% block title %}base{% endblock %}</title>

    <!-- Bootstrap -->
    <link href="{% static 'bootstrap-3.3.7-dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'font-awesome/css/font-awesome.min.css' %}" rel="stylesheet">
    <style>
        table th {
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
        }
    </style>
    {% block css %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Brand</a>
        </div>
        {% if request.session.user_id %}
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li class="active"><a href="{% url 'account:index' %}">主页</a></li>
                <li><a href="{% url 'question_bank:bank_list' %}">题库 <span class="sr-only">(current)</span></a></li>
                <li><a href="#">Link2</a></li>

            </ul>
            <form class="navbar-form navbar-left">
                <div class="form-group">
                    <input type="text" class="form-control" placeholder="Search">
                </div>
                <button type="submit" class="btn btn-default">Submit</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">欢迎, {{ request.user_info.user.username }}</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">Dropdown <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Action</a></li>
                        <li><a href="#">Another action</a></li>
                        <li><a href="{% url 'account:send_change_password_mail' %}">修改密码</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="{% url 'account:logout' %}">注销</a></li>
                    </ul>
                </li>
            </ul>
        {% else %}
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'account:login' %}">登录</a></li>
                <li><a href="{% url 'account:register' %}">注册</a></li>
            </ul>
        {% endif %}
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>

{% block content %}{% endblock %}

</body>
<script src="{% static 'js/jquery-3.2.1.js' %}"></script>
<script src="{% static 'ckeditor/ckeditor-init.js' %}"></script>
<script src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
<script src="{% static 'bootstrap-3.3.7-dist/js/bootstrap.min.js' %}"></script>
{% block js %}
{% endblock %}
</html>

account/templates/change_password.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>修改密码</title>
</head>
<body>
<form method="post">
    {% csrf_token %}
    {% for field in form %}
        <div class="form-group">
            <label for="{{ field.id_for_label }}">{{ field.label }}</label>
            {{ field }}
            <p class="text-danger">{{ field.errors.as_text }}</p>
        </div>
    {% endfor %}
    <input type="hidden" name="token" value="{{ token }}" style="">
    <input type="submit" value="提交">

</form>
</body>
</html>

account/templates/common_msg.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    {% if next_pg %}
        <meta http-equiv="refresh" content="5;url={{ next_pg }}">
    {% endif %}
    <title>消息</title>
</head>
<body>
{{ msg }}
</body>
</html>

account/templates/confirm.html
{% extends 'base.html' %}
{% block title %}注册确认{% endblock %}
{% block content %}
    <div class="row">
        <h1 class="text-center">{{ message }}</h1>
    </div>
    <script>
        window.setTimeout("window.location='/login/'",8000);
    </script>
{% endblock %}

account/templates/index.html
{% extends 'base.html' %}
{% block title %}主页{% endblock %}
{% block content %}
    {% if request.session.user_id %}
        <h1>你好，{{ request.user_info.user.username }} 欢迎回来！</h1>
    {% else %}
        <h1>你尚未登录，只能访问公开内容！</h1>
    {% endif %}
{% endblock %}

account/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% block title %}登录{% endblock %}
{% block css %}
    <link href="{% static 'css/login.css' %}" rel="stylesheet"/>{% endblock %}


{% block content %}
    <div class="container">
        <div class="col-md-4 col-md-offset-4">
            <form class='form-login' action="{% url 'account:login' %}" method="post">
                {% csrf_token %}
                <h2 class="text-center">用户登录</h2>
                {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        <p class="text-danger">{{ field.errors.0 }}</p>
                    </div>
                {% endfor %}
                <div class="col-xs-5 pull-left">
                    <img src="{% url 'account:image_code' %}" id="imageCode" title="点击更换图片">
                </div>
                <a class="pull-right" href="{% url 'account:forget' %}">忘记密码</a>
                <button type="submit" class="btn btn-primary pull-right">提交</button>
            </form>
        </div>
    </div> <!-- /container -->
{% endblock %}

{% block js %}
    <script>
        $(function () {
            $('#imageCode').click(function () {
                var oldSrc = $(this).attr('src');
                $(this).attr('src', oldSrc + "?");
            })
        })
    </script>
{% endblock %}

account/templates/register.html
{% extends 'base.html' %}
{% block title %}注册{% endblock %}
{% block content %}
    <div class="container">
        <div class="col-md-4 col-md-offset-4">
            <form class='form-register' action="{% url 'account:register' %}" method="post">
                {% csrf_token %}
                <h2 class="text-center">新用户注册</h2>
                {% for field in form %}
                    <div class="form-group">
                        <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                        {{ field }}
                        <p class="text-danger">{{ field.errors.as_text }}</p>
                    </div>
                {% endfor %}
                <button type="reset" class="btn btn-default pull-left">重置</button>
                <div class="col-xs-5">
                    <img src="{% url 'account:image_code' %}" id="imageCode" title="点击更换图片">
                </div>
                <button type="submit" class="btn btn-primary pull-right">提交</button>
            </form>
        </div>
    </div> <!-- /container -->
{% endblock %}