examOnline/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('account/', include(('account.urls', 'account'), namespace='account')),
                  path('question_bank/', include(('question_bank.urls', 'question_bank'), namespace='question_bank')),
                  re_path(r'^ckeditor/', include('ckeditor_uploader.ckeditor_urls')),
                  # 此处修改ckeditor源码取消验证url.py改成ckeditor_urls，将staff_member_required去掉
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  # 没有这一句无法显示上传的图片

question_bank/urls.py
from django.urls import path, re_path
from question_bank.views import bank
from question_bank.views import question

urlpatterns = [
    # 题库
    path('bank_list/', bank.bank_list, name='bank_list'),
    path('bank_add/', bank.bank_add, name='bank_add'),
    re_path(r'bank_edit/(?P<pk>\d+)/$', bank.edit, name='bank_edit'),
    re_path(r'bank_delete/(?P<pk>\d+)/$', bank.delete, name='bank_delete'),
    # 题
    path('question_list/', question.question_list, name='question_list'),
    re_path(r'question_add/', question.question_add, name='question_add'),
    re_path(r'question_edit/(?P<pk>\d+)/$', question.question_change, name='question_edit'),
    path(r'get_question_options/', question.get_question_options, name='get_question_options'),
    re_path(r'question_delete/(?P<pk>\d+)/$', question.question_delete, name='question_delete'),
    path('import_question/', bank.import_question, name='import_question'),
]

utils/urls.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from django.urls import reverse
from django.http import QueryDict


def memory_url(request, name, *args, **kwargs):
    """
    生成带有原搜索条件的URL（替代了模板中的url）
    :param request:
    :param name:
    :return:
    """
    basic_url = reverse(name, args=args, kwargs=kwargs)

    # 当前URL中无参数
    if not request.GET:
        return basic_url

    query_dict = QueryDict(mutable=True)
    query_dict['_filter'] = request.GET.urlencode()  # mid=2&age=99

    return "%s?%s" % (basic_url, query_dict.urlencode())


def memory_reverse(request, name, *args, **kwargs):
    """
    反向生成URL
        http://127.0.0.1:8001/rbac/menu/add/?_filter=mid%3D2
        1. 在url中讲原来搜索条件，如filter后的值
        2. reverse生成原来的URL，如：/menu/list/
        3. /menu/list/?mid%3D2

    示例：
    :param request:
    :param name:
    :param args:
    :param kwargs:
    :return:
    """
    url = reverse(name, args=args, kwargs=kwargs)
    origin_params = request.GET.get('_filter')

    if origin_params:
        url = "%s?%s" % (url, origin_params,)

    return url

question_bank/models.py
from django.db import models
from account.models import User
from ckeditor_uploader.fields import RichTextUploadingField


# Create your models here.
class QuestionBank(models.Model):
    # 题库
    title = models.CharField(verbose_name='标题', max_length=32)
    content = models.CharField(verbose_name='介绍', max_length=32)
    # sort_num = models.CharField(verbose_name='标题', max_length=32)
    created_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    post_state = models.BooleanField(verbose_name='发布状态', default=True)
    is_valid = models.BooleanField(verbose_name='是否可用', default=True)
    cover = models.ImageField(verbose_name='封面', upload_to='image/%Y%m', default='image/default.png', max_length=100)
    user_id = models.IntegerField(verbose_name='创建用户ID', default=0)
    subject_name = models.CharField(verbose_name='科目名', max_length=32)

    def count(self):
        num = Question.objects.filter(question_bank=self).count()
        if not num:
            return 0
        return num

    def __str__(self):
        return self.title


question_type_choice = [
    (1, '单选题'),
    (2, '多选题'),
    (3, '判断题'),
    (4, '填空题'),
    (5, '简答题'),
    (6, '综合题'),
]


class Question(models.Model):
    # 题
    question_bank = models.ForeignKey(verbose_name='关联题库', to='QuestionBank', on_delete=models.CASCADE)
    # subject_id = models.CharField(verbose_name='标题', max_length=32)
    type = models.SmallIntegerField(verbose_name='题目类型', choices=question_type_choice)
    # title = models.CharField(verbose_name='题目', max_length=512)
    title = RichTextUploadingField(verbose_name='题目', max_length=1024)
    analysis = models.TextField(verbose_name='解析', max_length=1024)
    sort_num = models.IntegerField(verbose_name='排序')
    update_time = models.DateTimeField(verbose_name='更新时间', auto_now=True)
    created_time = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    is_valid = models.BooleanField(verbose_name='是否可用', default=True)
    user_id = models.IntegerField(verbose_name='创建用户ID', default=0)

    def options(self):
        option_dict = ChoiceOptions.objects.filter(question=self).values()
        return option_dict

    def answer(self):
        res = ChoiceOptions.objects.filter(question=self, is_answer=True).values()
        return res


class ChoiceOptions(models.Model):
    # 选项
    question = models.ForeignKey(verbose_name='题目选项', to='Question', on_delete=models.CASCADE)
    title = models.CharField(verbose_name='选项标题', max_length=8)
    content = models.CharField(verbose_name='选项内容', max_length=256)
    is_answer = models.BooleanField(verbose_name='是否是正确答案', default=False)


class ImportFile(models.Model):
    file = models.FileField(upload_to='uploads/question_dir/%Y/%m/%d/')
    name = models.CharField(max_length=50, verbose_name=u'文件名')
    user = models.ForeignKey(verbose_name='上传者', to=User, on_delete=models.CASCADE)
    ctime = models.DateTimeField(verbose_name='上传时间', auto_now_add=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

question_bank/forms/bank.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from django import forms
from question_bank import models
from question_bank.forms.bootstrap import BootStrapForm


class BankAddModelForm(BootStrapForm, forms.ModelForm):
    class Meta:
        model = models.QuestionBank
        fields = ['title', 'content', 'cover', 'subject_name']

question_bank/forms/bootstrap.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-

class BootStrapForm(object):
    bootstrap_class_exclude = []

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            if name in self.bootstrap_class_exclude:
                continue
            old_class = field.widget.attrs.get('class', "")
            field.widget.attrs['class'] = '{} form-control'.format(old_class)
            field.widget.attrs['placeholder'] = '请输入%s' % (field.label,)

#
# class Foo(BootStrapForm):
#     pass
#
# obj = Foo()

question_bank/forms/question.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
import random
from django import forms
from question_bank import models
from question_bank.forms.bootstrap import BootStrapForm


class QuestionAddModelForm(BootStrapForm, forms.ModelForm):
    attr = {
        'class': 'form-control',
        'placeholder': "请输入解析",
        'cols': 40,
        'rows': 2,
        'maxlength': 1024
    }
    analysis = forms.CharField(label='解析', widget=forms.Textarea(attrs=attr), required=True)

    class Meta:
        model = models.Question
        fields = ['sort_num', 'type', 'title', 'analysis']


class QuestionEditModelForm(BootStrapForm, forms.ModelForm):
    attr = {
        'class': 'form-control',
        'placeholder': "请输入解析",
        'cols': 40,
        'rows': 2,
        'maxlength': 1024
    }
    analysis = forms.CharField(label='解析', widget=forms.Textarea(attrs=attr), required=True)
    type = forms.CharField(label='hide', widget=forms.HiddenInput)

    class Meta:
        model = models.Question
        exclude = ['user_id', 'is_valid']

question_bank/forms/upload_file.py
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from django import forms
from question_bank import models
from question_bank.forms.bootstrap import BootStrapForm
from django.forms import ValidationError


class UploadFileModelForm(BootStrapForm, forms.ModelForm):
    class Meta:
        model = models.ImportFile
        fields = ['file']

    def clean_file(self):
        file = self.cleaned_data['file']
        ext = file.name.split('.')[-1]
        if ext not in ('xls', 'xlsx'):
            raise ValidationError("文件格式不正确，支持格式('xls','xlsx')")
        return file

question_bank/views/bank.py
import uuid, os
from django.shortcuts import render, HttpResponse, redirect
from django.http import JsonResponse
from question_bank import models
from question_bank.forms.bank import BankAddModelForm
from django.urls import reverse
from django.db import transaction
from openpyxl import load_workbook
from question_bank.forms.upload_file import UploadFileModelForm
from utils.pagination import Pagination
from django.conf import settings


# Create your views here.
def bank_list(request):
    if request.method == 'GET':
        banks = models.QuestionBank.objects.filter(is_valid=True).all()
        print(banks)
        all_count = models.QuestionBank.objects.filter(is_valid=True).count()
        print(all_count)
        query_params = request.GET.copy()
        query_params._mutable = True
        pager = Pagination(
            current_page=request.GET.get('page'),
            all_count=all_count,
            base_url=request.path_info,
            query_params=query_params,
            per_page=settings.PER_PAGE_COUNT,
        )
        bank_data_list = banks[pager.start:pager.end]
        return render(request, 'bank_list.html', {'banks': bank_data_list, 'pager': pager})


def bank_add(reqeust):
    if reqeust.method == 'GET':
        form = BankAddModelForm()
        return render(reqeust, 'change.html', {'form': form})
    form = BankAddModelForm(data=reqeust.POST)
    if form.is_valid():
        title = form.cleaned_data.get('title')
        content = form.cleaned_data.get('content')
        cover = form.cleaned_data.get('cover')
        subject_name = form.cleaned_data.get('subject_name')
        models.QuestionBank.objects.create(title=title, content=content, cover=cover, subject_name=subject_name)
        return redirect('question_bank:bank_list')
    return render(reqeust, 'change.html', {'form': form})


def edit(request, pk):
    response = {'status': 'success'}
    bank_obj = models.QuestionBank.objects.filter(id=pk).first()
    if not bank_obj:
        response = {'status': 'error', 'msg': '未找到此条目'}
        return JsonResponse(response)
    if request.method == 'GET':
        response['id'] = bank_obj.id
        response['title'] = bank_obj.title
        response['content'] = bank_obj.content
        response['subject_name'] = bank_obj.subject_name
        return JsonResponse(response)
    title = request.POST.get('title', '')
    content = request.POST.get('content', '')
    subject_name = request.POST.get('subject_name', '')
    if all((title, content, subject_name)):
        response['title'] = title
        response['content'] = content
        response['subject_name'] = subject_name
        bank_obj.title = title
        bank_obj.content = content
        bank_obj.subject_name = subject_name
        bank_obj.save()
        return JsonResponse(response)
    response = {'status': 'error', 'msg': '数据不能为空'}
    return JsonResponse(response)


def delete(request, pk):
    # origin_list_url = self.reverse_list_url(*args, **kwargs)
    origin_list_url = reverse('question_bank:bank_list')
    if request.method == 'GET':
        return render(request, 'bank_delete.html', {'cancel': origin_list_url})
    models.QuestionBank.objects.filter(pk=pk).delete()
    return redirect(origin_list_url)


def load_question(file):
    wb = load_workbook(filename=file)
    sheet_names = wb.sheetnames
    ws = wb[sheet_names[0]]
    max_row = ws.max_row
    max_column = ws.max_column
    all_list = []
    lis = []
    for row in range(1, max_row + 1):
        dic = {}
        for column in range(1, max_column + 1):
            if row == 1:
                lis.append(ws.cell(row, column).value)
                continue
            dic.setdefault(lis[column - 1], ws.cell(row, column).value)
        if row > 1:
            all_list.append(dic)
    headers = ['bank_title', 'bank_content', 'type', 'title', 'analysis', 'sort_num']
    bank_name = None
    for q_dic in all_list:
        if not all(q_dic.values()) and not q_dic['type']:
            continue
        imp_bank_name = q_dic['bank_title'].strip()
        if bank_name != imp_bank_name:
            bank_name = imp_bank_name
            new_bank_obj = models.QuestionBank()
        new_question_obj = models.Question()
        try:
            with transaction.atomic():
                for key in headers:
                    if key.startswith('bank_'):
                        setattr(new_bank_obj, key.lstrip('bank_'), q_dic[key])
                    else:
                        setattr(new_question_obj, key, q_dic[key])
                        new_question_obj.question_bank = new_bank_obj  # 题与题库关联
                new_bank_obj.save()
                new_question_obj.save()
                if q_dic['type'] in (1, 2, 3):
                    answer = q_dic['answer'].upper().strip()
                    options = eval(q_dic['options'])
                    for option in options:
                        title = option.get('title')
                        if title.upper() == 'C' and q_dic['type'] == 3:
                            break
                        option_obj = models.ChoiceOptions()
                        content = option.get('content')
                        if title.upper().strip() == answer:
                            option_obj.is_answer = True
                        option_obj.title = title
                        option_obj.content = content
                        option_obj.question = new_question_obj  # 选项与题关联
                        option_obj.save()
        except Exception as e:
            print(q_dic)
            print(e)
            return False


def import_question(request):
    if request.method == 'GET':
        form = UploadFileModelForm()
        return render(request, 'test_page.html', {'form': form})
    form = UploadFileModelForm(request.POST, request.FILES)
    if form.is_valid():
        raw_file = form.cleaned_data.get("file")
        origin_name = raw_file.name
        ext = raw_file.name.split('.')[-1]
        new_name = '{}.{}'.format(uuid.uuid4().hex, ext)
        raw_file.name = new_name
        new_file_obj = models.ImportFile()
        new_file_obj.file = raw_file
        new_file_obj.name = origin_name
        new_file_obj.user_id = request.user_info.user.id
        new_file_obj.save()
        result = load_question(raw_file.open())
        if result is False:
            content = {'msg': '导入失败，3秒后跳转...', 'next_pg': reverse('question_bank:bank_list')}
        else:
            content = {'msg': '导入成功，3秒后跳转...', 'next_pg': reverse('question_bank:bank_list')}
        return render(request, 'common_msg.html', context=content)
    return render(request, 'test_page.html', {'form': form})

question_bank/templates/bank_delete.html
{% extends 'base.html' %}

{% block content %}
    <div class="luffy-container">
        <div class="alert alert-danger" role="alert">
            <form method="post">
                {% csrf_token %}
                <p style="font-size: 13px;"><i class="fa fa-warning" aria-hidden="true"></i> 删除后将不可恢复，请确定是否删除？</p>


                <div style="margin-top: 20px;">
                    <a href="{{ cancel }}" class="btn btn-default btn-sm">取消</a>

                    <input type="submit" class="btn btn-danger btn-sm" value="确 认">
                </div>
            </form>
        </div>
    </div>

{% endblock %}

question_bank/templates/bank_list.html
{% extends 'base.html' %}
{% load question %}
{% block css %}
    <style>
        table td {
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
        }


    </style>
{% endblock %}
{% block content %}

    <div class="container">
        <div class="btn-group" style="margin: 5px 0">

            <a class="btn btn-default" href="{% url "question_bank:bank_add" %}">
                <i class="fa fa-plus-square" aria-hidden="true"></i> 添加题库
            </a>
            <a class="btn btn-default" style="margin-left: 5px" href="{% url "question_bank:import_question" %}">
                <i class="fa fa-plus-square" aria-hidden="true"></i> 批量导入
            </a>
        </div>
        <table class="table table-bordered table-hover table-condensed">
            <thead>
            <tr>
                <th>序号</th>
                <th>封面</th>
                <th>题库名称</th>
                <th>简介</th>
                <th>所属科目</th>
                <th>题目数量</th>
                <th>创建时间</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for row in banks %}
                <tr>
                    <td>{{ forloop.counter }}</td>
                    <td>
                        <div class="cell" style="width: 40px; height: 18px;">
                            <a href="{% url 'question_bank:question_list' %}?bid={{ row.id }}">
                                <img src="{{ row.cover }}" alt="封面" class='img-rounded'
                                     style="object-fit: fill;vertical-align: top;width: 40px;height: 18px;">
                            </a>
                        </div>

                    </td>
                    <td><a href="#" data-toggle="modal" onclick="change('{% url 'question_bank:bank_edit' row.id %}')"
                           data-target="#myModal">{{ row.title }}</a></td>
                    <td>{{ row.content }}</td>
                    <td>{{ row.subject_name }}</td>
                    <td><a href="{% url 'question_bank:question_list' %}?bid={{ row.id }}">{{ row.count }}</a></td>
                    <td>{{ row.created_time }}</td>
                    <td>
                        <a href="{% url 'question_bank:question_add' %}?bid={{ row.id }}" style="color: #333333">添加题目<i
                                class="fa fa-edit"></i></a>
                        <a href="{% url 'question_bank:bank_delete' row.id %}" style="color: #333333"><i
                                class="fa fa-trash-o"></i></a>
                    </td>
                </tr>
            {% endfor %}
            {#            <tr>#}
            {#                <td><a href="#" data-toggle="modal" onclick="func('{% url 'question_bank:bank_edit' 1 %}')"#}
            {#                       data-target="#myModal">asdfas</a></td>#}
            {#            </tr>#}
            </tbody>
        </table>
        <nav>
            <ul class="pagination">
                {{ pager.page_html|safe }}
            </ul>
        </nav>
    </div>
    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">修改题库信息</h4>
                </div>
                <div class="modal-body">
                    <span></span>
                    <form>
                        <div class="form-group">
                            <label for="recipient-name" class="control-label">题库名称:</label>
                            <input type="text" class="form-control" id="bank-title" name="title" value="">
                        </div>
                        <div class="form-group">
                            <label for="recipient-name" class="control-label">简介:</label>
                            <input type="text" class="form-control" id="bank-content" name="content" value="">
                        </div>
                        <div class="form-group">
                            <label for="recipient-name" class="control-label">所属科目:</label>
                            <input type="text" class="form-control" id="bank-subject-name" name="subject_name" value="">
                        </div>
                    </form>


                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-primary" data-dismiss="modal" id="changeCommit">修改</button>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

{% block js %}
    <script>
        var pk = 0;
        $('#changeCommit').click(
            function commitChange() {
                var url = "{% url 'question_bank:bank_edit' 0 %}".replace("0", pk); //todo
                var data = $('.modal-body form').serialize();
                console.log(data, typeof (data))
                $.ajax({
                    type: 'post',
                    async: true,
                    dataType: 'json',
                    beforeSend: function (xhr, settings) {
                        xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token }}");
                    },
                    url: url,
                    data: data,
                    success: function (res) {
                        if (res.status == 'success') {
                            console.log(res)
                            console.log(window.location.href)
                            {#window.location.href += ''#}
                        } else {
                            alert(res.msg)
                        }

                    },
                    error: function () {

                    }
                })
            }
        )

        function change(url) {
            // 获取模态对话框数据
            $.ajax({
                type: 'get',
                async: true,
                dataType: 'json',
                url: url,
                success: function (res) {
                    console.log(res)
                    if (res.status === 'success') {
                        $('.modal-body form').removeClass('hide')
                        $('.modal-body span').text('')
                        $('#changeCommit').removeAttr('disabled')
                        $('#bank-title').val(res.title)
                        $('#bank-content').val(res.content)
                        $('#bank-subject-name').val(res.subject_name)
                        pk = res.id
                    } else {
                        $('.modal-body form').addClass('hide')
                        $('.modal-body span').text(res.msg)
                        $('#changeCommit').attr('disabled', 'disabled')

                    }

                },
                error: function () {

                }
            })
        }
    </script>
{% endblock %}

question_bank/templates/change.html
{% extends 'base.html' %}

{% block content %}
    <form class="form-horizontal" method="post" novalidate>
        {% csrf_token %}

        {% for field in form %}
            <div class="form-group">
                <label class="col-sm-2 control-label">{{ field.label }}</label>
                <div class="col-sm-8">
                    {{ field }}
                    <span style="color: red;">{{ field.errors.0 }}</span>
                </div>
            </div>
        {% endfor %}

        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-8">
                <input type="submit" value="保 存" class="btn btn-primary">
            </div>
        </div>

    </form>
{% endblock %}

question_bank/templates/question_list.html
{% extends 'base.html' %}
{% load question %}
{% block css %}
    <style>
        tr {
            display: table-row;
            vertical-align: inherit;
            border-color: inherit;
        }

        .question_title {
            font-weight: 700;
            font-size: 16px;
        }

        .cell {
            display: inline-block;
            box-sizing: border-box;
            overflow: hidden;
            text-overflow: ellipsis;
            white-space: nowrap;
            word-break: break-all;
            line-height: 23px;
            padding-right: 10px;
        }
    </style>
{% endblock %}
{% block content %}

    <div class="container">
        <div class="btn-group" style="margin: 5px 0">

            <a class="btn btn-default" href="{% url 'question_bank:question_add' %}?bid={{ bid }}">
                <i class="fa fa-plus-square" aria-hidden="true"></i> 添加题目
            </a>
        </div>
        <table class="table table-hover" style="width: 1052px;">
            <thead>
            <tr>
                <th>编号</th>
                <th>题型</th>
                <th>题目</th>
                <th>答案</th>
                <th>创建时间</th>
                <th>操作</th>
            </tr>
            </thead>
            <tbody>
            {% for row in questions %}
                <tr>
                    <td>
                        <div class="cell" style="width: 50px">{{ forloop.counter }}</div>
                    </td>
                    <td>
                        <div class="cell" style="width: 60px">{{ row.get_type_display }}</div>
                    </td>
                    <td>
                        <div class="cell" style="width: 500px">
                            <span>{{ row.title |cut:'p' }}</span>
                        </div>
                    </td>
                    <td>
                        <div class="cell" style="width: 50px">
                            {% for answer in row.answer %}
                                {{ answer.title }}
                            {% endfor %}
                        </div>
                    </td>
                    <td>
                        <div class="cell" style="width: 150px">{{ row.created_time }}</div>
                    </td>
                    <td style="width: 60px">
                        <div class="cell">
                            <a href="{% memory_url request 'question_bank:question_edit' row.id %}" style="color: #333333">
                                <i class="fa fa-edit"></i>
                            </a>
                            <a href="{% memory_url request 'question_bank:question_delete' row.id %}" style="color: #333333">
                                <i class="fa fa-trash-o"></i>
                            </a>
                        </div>

                    </td>
                </tr>
                <tr style="display: none">
                    <td colspan="6" style="padding: 20px 50px">
                        <div class="question_title">{{ row.title|cut:'_x000D_'  | safe }}</div>
                        {% for option in row.options %}
                            <div class="options">
                                <div class="options_title" style="float: left"> {{ option.title }}、
                                </div>
                                <div class="options_content">
                                    <div class="content"><p>{{ option.content |safe }}</p></div>
                                </div>
                            </div>
                        {% endfor %}
                        <div class="answer">
                            <span class="answer_label">正确答案:</span>
                            <span class="answer_content">
                                {% for answer in row.answer %}
                                    {{ answer.title }}
                                {% endfor %}
                            </span>
                        </div>
                        <div class="analysis">
                            <span class="analysis_label">试题解析:</span>
                            <span class="analysis_content">{{ row.analysis |safe }}</span>
                        </div>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <nav>
            <ul class="pagination">
                {{ pager.page_html|safe }}
            </ul>
        </nav>
    </div>

{% endblock %}

{% block js %}
    <script>
        $("tr").click(function () {
            $(this).next().toggle()
        });
    </script>
{% endblock %}